# Generated by Django 6.0.8 on 2026-09-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_seed_model_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
