# Generated by Django 6.0.8 on 2026-09-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_syncrun_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unmatchedrecord',
            name='reason',
            field=models.CharField(choices=[('no_lmarena_match', 'No LMArena match'), ('no_aa_match', 'No Artificial Analysis match'), ('not_in_agent_set', 'Not in agent set'), ('ambiguous_match', 'Ambiguous match'), ('duplicate_model_name', 'Duplicate model name'), ('validation_failed', 'Validation failed'), ('missing_identity', 'Missing identity')], max_length=32),
        ),
    ]
